# This is a basic workflow with a docker container created by a dockerfile
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  workflow:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs some prints
      - name: Show version information of vm
        run: |
            cat /etc/os-release
            python3 --version
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Check out repository
        uses: actions/checkout@v2
      # Use own action: uses an own docker container created by a dockerfile with entrypoint.sh
      - name: Run docker container with test.py
        uses: ./.github/actions/my-action
      # Runs a test job at VM
      - name: Run test
        run: python3 test.py
      # Runs a build job
      - name: Build job
        run: python3 build.py
      # Build job
      - name: Upload result of build job
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: myfile.txt