# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dock:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a test job
      - name: haha
        run: ls
      - name: Check out repository
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: test
        uses: ./.github/actions/my-action
      # build job
      - name: Upload result of build job
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: myfile.txt
          
      # Runs a test job
      - name: Run test
        run: python3 test.py
